---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: shell
  script: centos2ol.sh

platforms:
  # This name is a bit odd as it will be added and
  # removed from the Chef Server multiple times during testing
  # It can be searched via keyword: chef-deploy

  - name: centos-6.10
    driver_config:
      box: bento/centos-6.10

  - name: centos-7.9
    driver_config:
      box: bento/centos-7.9

  - name: centos-8.3
    driver_config:
      box: bento/centos-8.3

suites:
  - name: default
    provisioner:
      arguments: ['-k']
    run_list:
    attributes:
    verifier:
      inspec_tests:
        - test/integration/default
  - name: uek
    run_list:
    attributes:
    verifier:
      inspec_tests:
        - test/integration/uek
  - name: nobest
    # Only run on EL7 where --skip-broken is exercised
    includes:
      - centos-7.9
    # Pre-install EPEL packages that have no exact OL equivalent version,
    # simulating a real server with 3rd-party packages that would cause
    # yum distro-sync to fail without --skip-broken.
    # CentOS 7 EOL: redirect yum to vault.centos.org before installing EPEL.
    lifecycle:
      pre_converge:
        - remote: >-
            sudo sed -i "s/^mirrorlist=/#mirrorlist=/g" /etc/yum.repos.d/CentOS-*.repo &&
            sudo sed -i "s|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*.repo &&
            sudo yum install -y epel-release &&
            sudo yum install -y htop jq
    verifier:
      inspec_tests:
        - test/integration/nobest
